# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0
LABEL maintainer="hugofpaiva"
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY ./aula2.war /usr/local/tomcat/webapps/